name: hirocare
description: "A project for help people to care their health."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: '1.0.1'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  curved_labeled_navigation_bar: ^2.0.2
  dropdown_button2: ^2.3.9
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  http: ^1.2.1
  liquid_pull_to_refresh: ^3.0.1
  provider: ^6.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
